stages:
  - build
  - test

build-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

test-latest:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
  allow_failure: true
