[package]
name = "guion"
version = "0.2.0-dev2"

authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

description = "flexible GUI framework"
categories = ["gui"]
keywords = ["gui","ui"]
license = "MIT OR Apache-2.0"

repository = "https://github.com/ferionve/guion"
readme = "README.md"

[dependencies]
qwutils = { version = "0.1.1", git = "https://github.com/qwertz19281/rust_utils", rev = "c828ec4d864524e8846f25fc34f17e606accf3cc" }
#qwutils = { path = "../qwutils" }