[package]
name = "guion"
version = "0.1.1"

authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

description = "flexible GUI framework"
categories = ["gui"]
keywords = ["gui","ui"]
license = "MIT OR Apache-2.0"

repository = "https://github.com/ferionve/guion"
readme = "README.md"

[dependencies]
qwutils = { version = "0.1.0", git = "https://github.com/qwertz19281/rust_utils", rev = "3dd92de46947d65ec59a3c2aa8a885d09171ad4c" }
#qwutils = { path = "../qwutils" }